### ISSUE TITLE
Copy Connection?

### ISSUE THREAD

**Issue by Extortioner01** [akardapolov/ASH-Viewer#16]
Hello, lost the copy connection button. Can you turn it back?

**Comment by akardapolov** [comment]
> Hello, lost the copy connection button. Can you turn it back?

Hi!

Done
https://github.com/akardapolov/ASH-Viewer/commit/ab4535c66c36f43b930a1a5c37d323966280c8b7

Please wait 4.0.1 release.

Thanks,
Alex.
