### ISSUE TITLE
compatibility with Oracle 18c

### ISSUE THREAD

**Issue by legrandlegrand** [akardapolov/ASH-Viewer#17]
Hello,

when trying to connect to a 18c database
using ashv-3.5.1-bin
I get error:
ORA-28040: No matching authentication protocol

After updating ojdbc6.jar JDBC driver to ojdbc8.jar
I get error:
SQL Exception occured while connection pool initialize: 
Can't find class for driver: oracle.jdbc.pool.OracleDataSource

Any Idea ?
Thanks in advance
Regards
PAscal

**Comment by legrandlegrand** [comment]
https://github.com/akardapolov/ASH-Viewer/pull/15
that means it is fixed, I just have to upgrade ;o)

thanks again for this great tool !

**Comment by akardapolov** [comment]
> #15
> that means it is fixed, I just have to upgrade ;o)
> 
> thanks again for this great tool !

Great!
