### ISSUE TITLE
Create new connection dialogue

### ISSUE THREAD

**Issue by ykh-siteimprove** [akardapolov/ASH-Viewer#18]
Please change in the "Connect to database..." window the button label from "Open jar" to "Open JDBC Driver jar"
... to be more intuitive

Please make "Edit" button instead of the checkbox "Edit"

Please provide a label with the sample URL. E.g.: "jdbc:oracle:thin:@HOST:PORT:SID"

**Comment by akardapolov** [comment]
Hi!

[https://github.com/akardapolov/ASH-Viewer/commit/a7bfa545a53dea5d34d99a3a42a5d4ec45a24552](Done)

Edit button instead of the checkbox added earlier.

Thanks,
Alex.

**Comment by akardapolov** [comment]
https://github.com/akardapolov/ASH-Viewer/releases/tag/v4.2.1
