### ISSUE TITLE
Add ability to view history without online connection to database

### ISSUE THREAD

**Issue by xtender** [akardapolov/ASH-Viewer#20]
Sometimes I have no direct connection to database, but I can ask to send me ashviewer data files, so I want to have an ability to see history without real connection

**Comment by akardapolov** [comment]
Hi!

Done
https://github.com/akardapolov/ASH-Viewer/commit/7153a4e227bfa4cc24512087111fe3976c4ef4f2

Thanks,
Alex.

**Comment by akardapolov** [comment]
Ready to use it: https://github.com/akardapolov/ASH-Viewer/releases/tag/v4.2.0
