### ISSUE TITLE
Top activity script

### ISSUE THREAD

**Issue by Azamat12586** [akardapolov/ASH-Viewer#21]
Hi
First I'm sorry my English.
I need to solve the following:
Please monitor the top requests, make constant requests and any deviations (new requests, etc.) please throw in the mail (Oracle Database).
In the end, I have to send the information as in the picture below

![top_activity](https://user-images.githubusercontent.com/51772989/59422619-7c635f00-8df2-11e9-8864-d85762e63249.JPG)

Привет
Мне поставили задачу: просьба мониторить топ запросы, составь постоянные запросы и любые отклонения (новые запросы и т.п.) просьба скидывать на почту.
т.е. я должен высылать информацию как на картинке выше

**Comment by akardapolov** [comment]
Hi!

This complex task hard to execute in this tool. Need a lot of time to do it.

You can choose automatic mode in 3 version and make screenshot's

![image](https://user-images.githubusercontent.com/537977/59425478-761fb380-8def-11e9-81d7-6b29d8d3bcd7.png)

Thanks,
Alex.
