### ISSUE TITLE
login

### ISSUE THREAD

**Issue by chuan717** [akardapolov/ASH-Viewer#24]
hi:
URL login is too cumbersome, I think the previous 3.5 version was more convenient

**Comment by akardapolov** [comment]
Hi!

This tool was made for advanced users, and jdbc url concept is a well known. It's just matter of habit for hackers :)

https://docs.oracle.com/cd/E11882_01/java.112/e16548/urls.htm#JJDBC08200

Anyway, thank you for feedback!

Thanks,
Alex.
