### ISSUE TITLE
Connection dialog 'Enterprise' should be 'Diagnostic Pack'

### ISSUE THREAD

**Issue by Airell** [akardapolov/ASH-Viewer#25]
Hello,

Using Enterprise features like ACTIVE_SESSION_HISTORY, DBA_HIST_* and AWR functionality is not something you can use if you only have an 'Enterprise' version. One needs to have payed for the Diagnostic pack option:

- The V$ACTIVE_SESSION_HISTORY dynamic performance view and its underlying table
- All data dictionary views beginning with the prefix DBA_HIST_
- The DBMS_WORKLOAD_REPOSITORY package is part of this pack.

In the login dialog one can choose 'Enterprise' or 'Standard', but Enterprise is not enough. I have seen customers using this tool, with 'Enterprise' option, but they do not have the 'Diagnostic' option, so therefor are not allowed to use it. They should have selected 'Standard'.

Is it possible to change the label (or drop down options) to something like 'Enterprise WITH Diagnostic pack license' (Yes/No) ?

I know it's a DBA's responsibility, but now it makes more clear that this is allowed to be used. A check for the 'CONTROL_MANAGEMENT_PACK_ACCESS' parameter is very luxury, and maybe the best way to push the responsibility to the DBA's.

The Diagnostic Pack option costs $7500 per CPU. I don't think you want to have troubles with this when customers think that selecting 'OracleEE' will be enough.

Regards, Airell.

**Comment by akardapolov** [comment]
Hi!

Done https://github.com/akardapolov/ASH-Viewer/commit/9921ba264950a8b8ea40611f727128c2fc4e79a3

>> I don't think you want to have troubles with this when customers think that selecting 'OracleEE' will be enough.

https://github.com/akardapolov/ASH-Viewer/blob/master/LICENSE
https://www.gnu.org/licenses/gpl-3.0.ru.html
see paragraph 15. Disclaimer of Warranty.

Thanks,
Alex.

**Comment by Airell** [comment]
Superb! Thank you.
