### ISSUE TITLE
При щелчке левой клавишей мыши на график перерисовывается область top sql & sessions

### ISSUE THREAD

**Issue by arkanovas** [akardapolov/ASH-Viewer#27]
т.е. происходит перезагрузка, хотя по факту новая область не выбирается.

**Comment by akardapolov** [comment]
Здравствуйте!

Есть такое, но для меня это не баг, фича :)
Удобно, не надо делать выборку диапазона повторно.

Thanks,
Alex.

**Comment by arkanovas** [comment]
Ладно, будем иметь в виду, лишний раз не щелкать, можно тогда закрыть.
