### ISSUE TITLE
Duplicate plan hash value tabs  in sql_id window on sql_text/plan tab

### ISSUE THREAD

**Issue by feagor** [akardapolov/ASH-Viewer#34]
Hello today i'm see a lot of same tabs in sql_id window on sql_text/plan tab
![1](https://user-images.githubusercontent.com/36843125/87243612-03449a00-c440-11ea-87bb-9d0d95611b8e.png)

**Comment by xtender** [comment]
Looks like you have a lot of child cursors with the same phv
