### ISSUE TITLE
Takes 5+min to launch the tool 

### ISSUE THREAD

**Issue by raghavtech** [akardapolov/ASH-Viewer#39]
the tool seem to pull the last 60min data from ash and becomes extremely slow to launch under load as it tries to load last 60min data.

can we get an option to load ash data start from the point of launch/click connect to database.

if the database is under heavy load from users. it takes large amount of time to start up

**Comment by akardapolov** [comment]
Hi!

It's true for heavy loaded database (hundreds connections per second).
You can use OracleSE mode while loading long running profile. It takes data from the point of launch.

Thanks,
Alex.
