### ISSUE TITLE
RAC Support Request

### ISSUE THREAD

**Issue by anjuls** [akardapolov/ASH-Viewer#4]
Hi,

This is awesome tool, is it possible to provide RAC support?  Will changing the v$ to gv$ views will do or is it harder than what it looks like. Curious to know why RAC support was not initially developed? 

Thank you,
Anjul

**Comment by akardapolov** [comment]
Hi!

Thank you :)

Well, it is not difficult but need some time.

You can try to login on each node of RAC cluster using ASH Viewer. Each copy of program shows node statistics of RAC.

Thanks,
Alex.

**Comment by anjuls** [comment]
Sure, let me try. :+1:

**Comment by yaboeing** [comment]
Alexander, 
Would you answer about supporting RAC for tool? Any plans? 
Tnx
