### ISSUE TITLE
Idea for OracleSE: filling the gaps with Statspack

### ISSUE THREAD

**Issue by FranckPachot** [akardapolov/ASH-Viewer#42]
Hi,
With OracleSE we have no data outside of the time when ASH-Viewer is connected. But we often have Statspack running maybe every hour or shorter (snap level 0 every 5 minutes is possible). I got the idea to fill the gaps with info from Statspack (waits events + CPU from time model) and normalizing that to look like ASH samples. But it seems that the visualization expects one sample per second, right? If I have, say, 2 active sessions in samples every 5 minutes it shows as very small spikes every 5 minutes.
Ideally, it would be great to be able to ingest aggregated data, with AAS count rather than deduplicating the samples from statspack to look like ASH. Do you think it is easy to adapt the graph vizualizer to that? 
I can provide the query on stats$system_event, stats$sys_time_model, stats$snapshot giving SAMPLE_TIME,SESSION_STATE,WAIT_CLASS,EVENT#,EVENT plus AAS for this sample/event and I think a union all to the current one is sufficient.
Franck

**Comment by akardapolov** [comment]
Hi!

Actually, in the current version you can feed ASHV with modified data and load ASH like data source using profiles. Like here: https://github.com/akardapolov/ASH-Viewer/commit/7334393dc2737ba1f29c8473675cf84b6b8e9ba0

So, I think for Statspack visualizing need to write special type of software. I had written prototype of that. It is primely used for custom ad-hoc monitoring to get more details for different subsystems, here example for ASM disk statistics:

![image](https://user-images.githubusercontent.com/537977/103098652-5ea0c800-462d-11eb-91c5-9c6d3859cff7.png)

Thanks,
Alex

**Comment by FranckPachot** [comment]
Ok, thanks.
