### ISSUE TITLE
Подключения 3-й ветки к Оракл 19С

### ISSUE THREAD

**Issue by AUbaydulloev** [akardapolov/ASH-Viewer#46]
Добрый день, спасибо Вам за Ваш труд! Приложения классная. 

Недавно обновили базу до 19С, после ASH Viewer 3.5 не подключается к БД. 
Скачали новую версию, но тут сессия зависает и не восстанавливается. 
Вопрос как настроить версию 3.5 так чтобы работало с Оракл 19С?
Спасибо.

**Comment by akardapolov** [comment]
Здравствуйте! 

Проверил 3 и 4 версии - работают c 19.3. 
Пришлите лог приложения, посмотрим что за ошибка (start.sh или start.cmd)
https://github.com/akardapolov/ASH-Viewer/blob/feature/run.bat
https://github.com/akardapolov/ASH-Viewer/blob/feature/run.sh

Thanks,
Alex.

**Comment by AUbaydulloev** [comment]
Спасибо за отклик!

Вложил скрин. 

![изображение_2021-05-22_140254](https://user-images.githubusercontent.com/84558276/119220954-672afb00-bb06-11eb-9edc-394bb79856fa.png)

**Comment by akardapolov** [comment]
Попробуйте запустить 3.5.1.1 версию, файл по ссылке
https://github.com/akardapolov/ASH-Viewer/releases/tag/v3.5.1

**Comment by AUbaydulloev** [comment]
Спасибо, заработало.

**Comment by j7v-a4m** [comment]
Добрый день.
У меня 2 вопроса касательно 3.5.1.1 версии
1) Можно получить исходный код для этой версии? По этой ссылке (https://github.com/akardapolov/ASH-Viewer/releases/tag/v3.5.1) доступен только исходник для 3.5.1 
2) За счет чего 3.5.1.1 (3.5.1) может восстановить подключение к бд, что 4 версии не могут? Может это можно внедрить и в 4 версию?

Заранее спасибо за помощь.
