### ISSUE TITLE
Невозможно подключиться к базе. версия 4.3.1

### ISSUE THREAD

**Issue by feagor** [akardapolov/ASH-Viewer#47]
Добрый день. 
Сразу 2 связанных проблемы:
1. Невозможно подключиться к базе после закрытия приложения. В окне подключения красуется надпись Running без возможности входа. Даже в оффлайн режиме, чтобы посмотреть историю. Чтобы войти приходится копировать соединение. Возможно это происходит в следствии:
2. После того как рвется соединение с базой, например при выключении базы, приложение не восстанавливает соединение после того, как база становится доступной. Версия 3.5.1 даже после обрыва соединения умудряется его восстановить и нормально продолжать снимать активность.
![изображение](https://user-images.githubusercontent.com/36843125/119513378-d6118980-bd7c-11eb-85ba-5f93b648c645.png)

**Comment by akardapolov** [comment]
Добрый день.

1. В конфиге подключения (директория configuration) ставим running: false. Такое бывает когда процесс завершается извне. Если останавливать штатно, настройка статуса корректно устанавливается и потом можно подключаться.
2. Известная проблема, пока нет времени чтобы реализовать функциональность.

Thanks,
Alex.

**Comment by feagor** [comment]
Спасибо, помогло
