### ISSUE TITLE
How to order/sort the configured databases?

### ISSUE THREAD

**Issue by SheldonBlu** [akardapolov/ASH-Viewer#52]
Hi Alex.  Great tool.  I have many databases still to configure.  How/where can we alphabetically sort the list of configured databases?

![image](https://user-images.githubusercontent.com/33632333/139109312-86db17d6-78bd-483f-b399-f43e8c9b918e.png)

**Comment by DamirVa** [comment]
In last version 4.4.1-bin this is exactly like this...so solved!
