### ISSUE TITLE
Top sql & sessions, Raw data, ASH report blank

### ISSUE THREAD

**Issue by wayneadamsconsulting** [akardapolov/ASH-Viewer#60]
Just downloaded and installed latest version of ASH Viewer.    Running jre 1.8_221 and latest ojdb8.jar.    The main Active Sessions graph shows fine, but the 3 bottom panels (Top sql & sessions, Raw Data, ASH Report) are all blank.   Tested against a 19c RAC database and an 11.2.0.4 standalone db
![2022-04-27_11h34_50](https://user-images.githubusercontent.com/25396082/165595883-e0caea94-be65-4f45-8794-3277c67141a5.png)
.

**Comment by akardapolov** [comment]
Hi!

Try to select range in Top activity chart.

Thanks,
Alex.

**Comment by wayneadamsconsulting** [comment]
Ahh!  Thanks!  Seems obvious now, I'm used to the OEM Ash Analytics where the last 5 min is automatically selected.   Might want to add a brief change to the intro docs.  "Press Connect button and start to monitor your system, and highlight a range to show details".
