### ISSUE TITLE
Need Minimalistic Mode in version 3.5

### ISSUE THREAD

**Issue by SamatIsabaev** [akardapolov/ASH-Viewer#8]
In v. 3.5 I Cant find Minimalistic Mode

**Comment by akardapolov** [comment]
Hi!

Please, use 3.5.1 version.

https://sourceforge.net/projects/ashv/

![image](https://user-images.githubusercontent.com/537977/35796327-fef6c08c-0a7d-11e8-9c9e-5dcefba70e38.png)

**Comment by SamatIsabaev** [comment]
Thanks!
Where I can read new features in v. 3.5 and 3.5.1?

**Comment by akardapolov** [comment]
See commit log data since 2014-12-03:
https://github.com/akardapolov/ASH-Viewer/commits/master
